name: Documentation

on: [push]

permissions:
    contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme

      - name: Sphinx build
        run: |
          sphinx-build docs _build
          touch _build/.nojekyll

      - name: Deploy
        if: success()  &&  github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: _build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}