name: Linter

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Analysing the code with flake8
      run: |
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Build documentation
      run: |
        rm -rf ./docs/apidoc
        sphinx-apidoc src/ -o ./docs/apidoc --no-toc --separate --module-first
        sphinx-build docs sphinx
        touch sphinx/.nojekyll
    - name: Deploy documentation to GitHub Pages
        if: success()  &&  github.ref == 'refs/heads/main'
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: sphinx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}