name: Main action

on: [push, pull_request, workflow_dispatch]

permissions:
    contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run unit tests
        run: |
          pytest --cov-report lcov:/coverage/lcov.info --cov=.

      - name: Coveralls
        uses: coverallsapp/github-action@v1

      - name: Sphinx build
        run: |
          sphinx-apidoc -o docs DatAnalyzer/ --separate --module-first
          sphinx-build docs _build
          touch _build/.nojekyll

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
